version: "3"
services:
  db:
    image: mysql:latest
    restart: "always"
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin12345"
      MYSQL_DATABASE: "rdc-flask-crud"
      MYSQL_ROOT_PASSWORD: "admin12345"
    ports:
      - "3333:3306"
    expose:
      - "3306"
    volumes:
      - /home/caefleury/Documents/unb/mysql:/var/lib/mysql
